name: my_wordpress_app
description: "A new Flutter project."
publish_to: "none"
version: 0.0.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  provider: ^6.1.2
  dio: ^5.7.0
  collection: ^1.18.0
  intl: ^0.19.0
  shamsi_date: ^1.0.4
  persistent_bottom_nav_bar: ^6.2.1
  # flutter_native_splash: ^2.4.1
  loading_animation_widget: ^1.3.0
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
